### ISSUE TITLE
Use Vault rather than looping permission-check

### ISSUE THREAD

**Issue by Foorack** [MyzelYam/SuperVanish#31]
Fetch a users permission through Vault rather than looping the hasPermission function 100 times. It is spamming the console when inspecting permissions and it is also an inefficient way to code it.

**Comment by MyzelYam** [comment]
I agree with it being inefficient but there is no better way of doing it without sacrificing reliability and plugin support.
Using Vault doesn't help since its method to get a player permission state (Permission#has(player, permission);) just calls player#getPermission(..) so there is actually just an unnecessary overhead in using Vault for this, not to mention the hard dependency on Vault that would be required for this.
There is an alternative though, which is looping through Player#getEffectivePermissions(), but this may not be better in performance depending on how many permissions a player has and it's also not supported by all permissions plugins since some just replace the PermissibleBase object inside CraftHumanEntity to get full control over permissions.
I'm currently caching permission checks so there are only ~200 permission checks on login, not every x ticks. You can also change the amount of permission checks in the config file.
